- name: Build Templates
  hosts: ANSIBLE-AWX
  tasks:
  - name: Pull Builder Image
    docker_image:
      name: maartenmol/dhs-packer
      source: pull
  - name: Build Windows 10
    docker_container:
      name: build-windows-10
      auto_remove: "{{ removeAutomatic }}"
      image: maartenmol/dhs-packer
      command: ["packer build -force -var 'vcenter_pass=VD!fli9ht' -var-file 'vars_vcenter.json' Windows_10.json"]