---
- name: Prepare Bastion host
  hosts: bastions
  gather_facts: no
  tasks:
    - name: Create Bastion user with SSH-Keypair
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
    - name: Create the CP directory if it does not exist
      file:
        path: /root/.ssh/cp
        state: directory
    - name: Set authorized key taken from file
      shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    - name: Download SystemD service for Ansible SOCKS Proxy
      get_url:
        url: http://nexus.dhsnext.nl/repository/raw-dhs/systemd-services/ansible-proxy.service
        force: yes
        dest: /etc/systemd/system/ansible-proxy.service
        mode: '0644'
    - name: Start & Enable Ansible SOCKS Proxy
      systemd:
        name: ansible-proxy
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Add Ansible SOCKS Proxy Port to FirewallD
      firewalld:
        port: 4321/tcp
        permanent: yes
        state: enabled